name: flutter_dmzj
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  remixicon: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_smart_dialog: ^4.5.3+6
  flutter_staggered_grid_view: ^0.6.1
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.4
  webview_flutter: ^3.0.4
  flutter_widget_from_html_core: ^0.8.5+3
  multi_split_view: ^2.1.0
  tab_indicator_styler: 2.0.0
  crypton: ^2.0.5
  crypto: ^3.0.2
  logger: 1.1.0
  extended_image: 6.2.1
  flutter_swiper_view: 1.1.8
  flutter: 
    sdk: flutter
  flutter_easyrefresh: 
    git: 
      url: https://github.com/hkloudou/flutter_easyrefresh.git
      ref: v2-flutter3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

